### PR TITLE
[CoreBundle] - directive allowing to disable a link. closes #1199

### LINKED ISSUE #1199: [ExoBundle] - Player - Try Exercise button
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master

When trying an exercise the [Test exercise] link is (style) disabled but is still active.
If we navigate through steps and then click the link we go back to first step...

### PR DESCRIPTION
**Pull request by pitrackster**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | yes
| Fixed tickets | #1199

Core directive that allow to add a "disable" attribute on a link

### CODE REVIEW

File: plugin/exo/Resources/modules/exercise/module.js [hunk 1]
```diff
@@ -10,6 +10,7 @@ import 'angular-ui-tinymce'
 import 'angular-ui-translation/angular-translation'
 import '#/main/core/modal/module'
 import '#/main/core/fos-js-router/module'
+import '#/main/core/aDisabled/module'
```
Comment (Elorfin) [inline plugin/exo/Resources/modules/exercise/module.js]: Use same convention as other modules : `a-disabled`.
Also, i would have created a `link` module which could contain more than this sole directive.

File: plugin/exo/Resources/modules/exercise/module.js [hunk 2]
```diff
@@ -32,6 +33,7 @@ angular
     'ui.tinymce',
     'ui.modal',
     'mgcrea.ngStrap.datepicker',
+    'LinkDisabled',
```
Comment (Elorfin) [inline plugin/exo/Resources/modules/exercise/module.js]: Other core modules uses lowercase.

**Comment by LaurentGruber** [comment]
LGTM
